name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: 初始化环境
      run: |
        hdiutil create -size 20g -type SPARSE -fs "Case-sensitive HFS+" -volname OpenWrt OpenWrt.sparseimage
        hdiutil attach OpenWrt.sparseimage
        cd /Volumes/OpenWrt
        brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep wget quilt xz
    - name: 获取OpenWrt项目源码
      run: |
        ls -al
        git clone https://github.com/openwrt/openwrt.git
        ls -al
        cd openwrt
    - name: 更新并安装 feeds
      run: |
        cd openwrt
        ls -al
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 开始构建
      run: |
        make -j1 V=s
