name: 测试发布

on:
  push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
   
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_a_release.outputs.upload_url }}
        asset_path: ./diy.sh
        asset_name: ${{ steps.create_release.outputs.tag }}
        asset_content_type: application/zip
