name: 测试构建

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: 拉取项目文件
      uses: actions/checkout@v1
      
    - name: 初始化环境
      run: |
        echo 创建APFS HFS+宗卷
        hdiutil create -size 20g -type SPARSE -fs "Case-sensitive HFS+" -volname OpenWrt OpenWrt.sparseimage
        hdiutil attach OpenWrt.sparseimage
        echo 安装构建所需依赖
        #cd /Volumes/OpenWrt
        #brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep wget quilt xz
        brew install gnu-tar findutils coreutils gawk grep gnu-getopt
        echo "::add-path::/usr/local/opt/gnu-getopt/bin"
    
    - name: 初始化OPENWRT项目文件
      run: |
        echo 获取 OpenWrt 项目源码...
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        echo 更新并安装 Feeds...
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo 初始化配置文件...
        make defconfig
        
      working-directory: /Volumes/OpenWrt

    - name: 下载 package
      run: |
        echo -e "$(nproc) 线程下载"
        make download -j$(nproc)
      working-directory: /Volumes/OpenWrt/openwrt
    - name: 打包文件
      run: |
        ls
        #zip os.zip ./bin/targets/*/*/*.*
        zip os.zip ./openwrt
      working-directory: /Volumes/OpenWrt
      
    - name: 创建发布
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.sha }}
        release_name: Release ${{ github.sha }}
    
    - name: 上传发布资源
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./os.zip
        asset_name: 固件.zip
        asset_content_type: application/zip
    
    - name: 开始多线程构建
      run: |
        echo -e "$(nproc) 线程编译"
        make -j$(nproc)
      working-directory: /Volumes/OpenWrt/openwrt
      
    - name: 单线程编译
      if: failure()
      run: |
        make -j1 V=s
      working-directory: /Volumes/OpenWrt/openwrt
