name: 测试发布

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: 测试
      run: |
        ls
    - name: Create a Release
      uses: actions/create-release@v1
      with:
    # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: github.GITHUB_REF
    # The name of the release. For example, `Release v1.0.1`
        release_name: Release v1.0.1
    # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
        draft: false
    # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
        prerelease: false
